services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
      # CORREÇÃO AQUI: Mapeia o diretório inteiro em vez do arquivo
      - ./backend/data:/code/data
    environment:
      # O caminho para o banco de dados agora está em um subdiretório
      - DATABASE_URL=sqlite:///./data/app.db
      - CORS_ORIGINS=http://localhost:5173,http://localhost
    
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules